#!/bin/zsh
case $1 in
    svs )
        case $2 in
            test )
                # Runs the standard SVS tests
                # param 2: The changeset Id
                svs submit -n -c $2
                ;;

            submit )
                # Runs the standard SVS tests and commits the changes
                # param 2: The changeset Id
                svs commit -c $2
                ;;

            help )
                echo "Options: test, submit"
                ;;
        esac
        ;;

    nimbus )
        case $2 in
            deploy )
                # Deploys 1 vcenter instance and 2 esx instances into nimbus
                # param 3: The changelist Id for vcenter (optional)
                # param 4: The changelist Id for esx (optional)
                test-vpx --vc-build=$(query build vc $3) --esx-build=$(query build vc $4) --num-esx-hosts=2 --deploy-only
                ;;

            load-vc )
                # Loads the deployed vcenter server with the local build
                # param 3: The Id of the vcenter instance to update (optional)
                load-vc -I $(query nimbus ip vc $3) -i -p vmware
                ;;

            fix-vc )
                # Repairs the vc db so that load-vc can be run again
                # param 3: The Id of the vcenter instance to update (optional)
                ssh root@$(query nimbus ip vc $3) -e "/usr/sbin/vpxd -b"
                ;;

            ssh )
                case $3 in
                    vc )
                        # Creates an SSH session into the vceneter instance
                        # param 4: The Id number of the esx server (optional)
                        ssh root@$(query nimbus ip vc $4)
                        ;;

                    esx )
                        # Creates an SSH session into the esx instance
                        # param 4: The Id number of the esx server (optional)
                        ssh root@$(query nimbus ip esx $4)
                        ;;

                    help )
                        echo "Options: vc, esx"
                        ;;
                esac
                ;;

            help )
                echo "Options: deploy, load-vc, fix-vc, ssh"
                ;;
        esac
        ;;

    review )
        case $2 in
            size-diff )
                # Gets the difference in executable size for the given changes
                # param 3: The starting changeset Id
                # param 4: The ending changeset Id
                vpxd-size $3 $4
                ;;

            update-cl )
                # Updates the changelist with size-diff and other info
                ;;

            post )
                # Generates a review board post with all of the correct information filled in
                ;;

            help )
                echo "Options size-diff, update-cl, post"
                ;;
        esac
        ;;

    * )
       # Invalid argument
       echo "Help: please choose svs, nimbus, or review"
       ;;
esac
